# Generated by Django 2.2.5 on 2019-10-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEmEstabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEmPontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('localizacao', models.CharField(max_length=128)),
                ('descricao', models.CharField(max_length=128)),
                ('categoria', models.CharField(max_length=128)),
                ('funcionamento', models.TimeField()),
                ('gostei', models.IntegerField()),
                ('nao_gostei', models.IntegerField()),
                ('comentarios', models.ManyToManyField(through='web.ComentarioEmEstabelecimento', to='web.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('localizacao', models.CharField(max_length=128)),
                ('descricao', models.CharField(max_length=300)),
                ('acesso', models.CharField(max_length=124)),
                ('valor', models.FloatField()),
                ('gostei', models.IntegerField()),
                ('nao_gostei', models.IntegerField()),
                ('dicas', models.CharField(max_length=128)),
                ('comentarios', models.ManyToManyField(through='web.ComentarioEmPontoTuristico', to='web.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('idade', models.IntegerField()),
                ('cidade', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Comentario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PontoTuristicoEmGuiaTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia_turistico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.GuiaTuristico')),
                ('ponto_turistico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.PontoTuristico')),
            ],
        ),
        migrations.AddField(
            model_name='guiaturistico',
            name='local_de_atendimento',
            field=models.ManyToManyField(through='web.PontoTuristicoEmGuiaTuristico', to='web.PontoTuristico'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('local', models.CharField(max_length=128)),
                ('horario', models.DateTimeField()),
                ('descricao', models.CharField(max_length=300)),
                ('estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Estabelecimento')),
            ],
        ),
        migrations.AddField(
            model_name='comentarioempontoturistico',
            name='ponto_turistico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.PontoTuristico'),
        ),
        migrations.AddField(
            model_name='comentarioemestabelecimento',
            name='establecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ManyToManyField(through='web.UsuarioEmComentario', to='web.Usuario'),
        ),
    ]
